name: mario
version: 1.0.8
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.0.1
  geolocator: ^11.0.0
  loading_animation_widget: ^1.2.0+4
  device_info_plus: ^9.1.2
  flutter_inappwebview: ^6.0.0
  change_app_package_name: ^1.1.0
  rename: ^3.0.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  firebase_core: ^2.24.2
  get_storage: ^2.1.1
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
